### ISSUE TITLE
Send room_temperature from HA to ViCare

### ISSUE THREAD

**Issue by amgstone** [oischinger/ha_vicare#101]
Tel me how to send room_temperature from HA to ViCare
![qwe](https://user-images.githubusercontent.com/63303107/184620818-a7387eaf-8fec-4eb6-abc5-a02fafa8555e.jpg)

**Comment by oischinger** [comment]
Unfortunately that's not possible. The Viessmann API doesn't allow this

**Comment by oischinger** [comment]
Oh, sorry. It seems it is actually possible. Needs to be implemented first

**Comment by amgstone** [comment]
thank you, we will wait for implementation, the most important thing is that you can transfer the average temperature there

**Comment by amgstone** [comment]
when can we expect a plugin update?

**Comment by woehrl01** [comment]
It looks like your device is not returning the room temperature at all or via the correct endpoint. What's you exact setup? Are you sure your device returns the actual room temperature (please verify via the ViCare app)?

**Comment by woehrl01** [comment]
That's not possible at all.

**Comment by amgstone** [comment]
is it not possible to transfer values ​​from HA to Vicare via api?

**Comment by woehrl01** [comment]
No, only the other way around.

**Comment by oischinger** [comment]
Ok, then Inwas right after all. It's not possible with the Viessmann API.

The room temperature data is already implemented in HA but as @woehrl01 stated it works the other way around
