### ISSUE TITLE
Boiler and distribution manifold temperature

### ISSUE THREAD

**Issue by amgstone** [oischinger/ha_vicare#102]
What is the difference between those 2 temperature sensors, they show the same value for me sensor.pyvicare_supply_temperature, sensor.pyvicare_boiler_temperature

**Comment by woehrl01** [comment]
That depends on the device. Often in that case it can show the same temperature.

Supply is the temperature in the device, boiler the temperature of the boiler. Of there is no external boiler its likely the same.
