### ISSUE TITLE
Error setting up entry ViCare for vicare

### ISSUE THREAD

**Issue by paradix** [oischinger/ha_vicare#105]
Based on the issue https://github.com/home-assistant/core/issues/77050
I have exactly the same problem since updating to  Home Assistant 2022.8.5

**Comment by oischinger** [comment]
Can you please try to delete the locally saved token via
`rm /config/.storage/vicare_token.save`

and restart HA or re-configure the integration?

**Comment by paradix** [comment]
@oischinger It worked! Thnx a lot

**Comment by oischinger** [comment]
Closing this one. We have a HA Core issue as well
