### ISSUE TITLE
mismatch with HA energy dashboard. Sensors no more have unit of measurment 

### ISSUE THREAD

**Issue by phd59** [oischinger/ha_vicare#106]
it seems that since an update (august/september), it is no more possible to get gas consumed into the energy dashboard.

That worked fine previously: I used to fill it with sensor.vicare_heating_gas_consumption_today and sensor.vicare_hot_water_gas_consumption_today

But these two sensors no more have unit kWh, and so they are no more available in dropdown list of sensors “add a gas source” when setting up energy dashboard.

Vitodens 200w - HA supervised 2022-09
No error in logs.

**Comment by woehrl01** [comment]
There has been a PR merged, a few days ago, to fix this in the underlying library, because of an api change: https://github.com/somm15/PyViCare/pull/264

**Comment by phd59** [comment]
Sorry for duplicate, I didnt find the previous PR. 
And very  great thanks for this job, it is the main part of my HA installation, especially now with all that happens on gas market ...
Go on guys !
