### ISSUE TITLE
Expand One Time Charge

### ISSUE THREAD

**Issue by PaulProjects** [oischinger/ha_vicare#107]
At the moment the integration ViCare features one button that "just" quietly turns on the "one time charge" feature of the viessmann device. There is currently no way to turn that feature off by using the integration or see if its already active.
PyViCare is a able to recive the current status of the "one time charge" feature and disable it like the viessmann app is able to do.

Relevant:
[https://github.com/somm15/PyViCare/issues/110#issuecomment-886594518](
https://github.com/somm15/PyViCare/issues/110#issuecomment-886594518)

Thoughts about what could be a good implementation:
Current state of "one time charge": binary_sensor.vicare_one_time_charge_active
Deactivate "one time charge": button.deactivate_one_time_charge (or button.vicare_deactivate_one_time_charge)

an even better maybe a bit more complex solution would be a switch that displays the current state and can alter the current state of "one time charge" : switch.vicare_one_time_charge

**Comment by lukx** [comment]
Duplicate of #96 
I am working on this again, kinda dropped the progress during summer as I preferred to investigate more on the sgReady Activation.

**Comment by PaulProjects** [comment]
thank you 👍🏻
