### ISSUE TITLE
Errors latest commit

### ISSUE THREAD

**Issue by meks007** [oischinger/ha_vicare#109]
Hi,

after updating to the latest commit [a26a46d](https://github.com/oischinger/ha_vicare/commit/a26a46d00392df9398f2c49c7a5f01dae37d7c9a) I get the following error. The only entity affected by that appears to be climate.vicare_heating.

```
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 18:30:50 (1 occurrences)
Last logged: 18:30:50

Unable to prepare setup for platform vicare.climate: Platform not found (cannot import name 'PRESET_COMFORT' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
```

<img width="782" alt="image" src="https://user-images.githubusercontent.com/23148641/193465991-10861019-2cec-4f48-90df-41802cdddae2.png">

**Comment by oischinger** [comment]
Hi @meks007  are you running the latest version of home assistant?
Some imports changed and the integration is only aligned with the current HA version

**Comment by meks007** [comment]
yeah, everything is at the latest available version

Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

Just checked, no updates available.

**Comment by oischinger** [comment]
oh, you're right. I am already on the beta of home assistant so I didn't notice. Sorry, I'll fix that!

**Comment by oischinger** [comment]
fixed with last commit

**Comment by meks007** [comment]
confirmed working, thanks!
