### ISSUE TITLE
Only one device found

### ISSUE THREAD

**Issue by emartinelis** [oischinger/ha_vicare#121]
Hello, I'm using Vitodens 100-W with integrated wifi module and VITOCONNECT OT2 with connected ViCare Wireless Thermostat & Climate sensors, everything is connected with ViCare and works fine, but  HomeAssistant finds only one device (Vitodens 100-W) is there any solution that both devices or at least OT2 with connected sensors would be found?

**Comment by woehrl01** [comment]
See #78.

**Comment by emartinelis** [comment]
This solution doesn't work. As I understand that's because I have 2 gateways, is there any possibility to select second gateway?

![image](https://user-images.githubusercontent.com/98991852/212050389-b66eb8fb-994f-4e1b-ad77-c30afec71d16.png)

**Comment by oischinger** [comment]
@emartinelis can you please check again eith the latest commits on that branch?

And irrelevant of the results it would be great if you could download diagnostics data on the integration page and provide it here for further analysis


Thanks

**Comment by emartinelis** [comment]
Still it finds only main heating system, also adding devices info:

[config_entry-vicare-794ae50dfacffca2768c059373ada34e.json.txt](https://github.com/oischinger/ha_vicare/files/10425753/config_entry-vicare-794ae50dfacffca2768c059373ada34e.json.txt)

![image](https://user-images.githubusercontent.com/98991852/212678585-70d8f8c7-b77e-4daa-84c4-08e40e8dace5.png)

![image](https://user-images.githubusercontent.com/98991852/212678757-fe66c2b5-8f85-420a-adf3-0bf11ec95f1d.png)

**Comment by oischinger** [comment]
@emartinelis I think it should work but I noticed a bug in the current implementation on the multi-device branch:
Can you select "auto" for the heating mode?
Otherwise the HA integration is unable to detect the correct device type for the thermostats

**Comment by oischinger** [comment]
tracked via https://github.com/oischinger/ha_vicare/issues/78
