### ISSUE TITLE
Power consumption heat pumps 

### ISSUE THREAD

**Issue by Toschi57** [oischinger/ha_vicare#124]
Hi Oischinger,

I created also a request in the home assistant forum. Not sure which place is better.

https://community.home-assistant.io/t/viessmann-component/77873/845

It would be very great if you can add the power consumption values for heat pumps.

In pyvicare it is implenented
https://github.com/somm15/PyViCare/commit/5b811324dc4169196e06c84635030aa1a5e8bd09

By the way, great work and a big Thank.

**Comment by robinostlund** [comment]
+1 on this request :)

**Comment by Benleni17** [comment]
+2 I need the value too :)

**Comment by bdejaeg** [comment]
+3 would like to have this too :)

**Comment by artur90226** [comment]
+4 please

**Comment by jerry-cross** [comment]
+5 Ditto please!
Although the gas sensor that appears seems to be doing the right thing just called the wrong name.
Thanks so much for your work

**Comment by meks007** [comment]
+6 please

**Comment by oischinger** [comment]
At least I wrote some tests that indicate so.

However the sensor name is not good. I'll change it in an upcoming release

```
-        name="Energy consumption of hot water gas heating current month",
+        name="Energy consumption of hot water heating current month",

```
