### ISSUE TITLE
Gridbox Power Heat Pump

### ISSUE THREAD

**Issue by Benleni17** [oischinger/ha_vicare#125]
Good morning,
I keep reading that members are looking for the power requirements of the Viessmann heat pump. I use the GridBox system from Viessmann, with which I can see the power requirement of the heat pump. Is it possible to migrate the values ​​in HA via the GridBox? The Gridbox is connected to my network via Modbus.

![Screenshot 2023-03-21 081541](https://user-images.githubusercontent.com/122219920/226539643-185fb00b-c01e-4b1f-8ee2-93d252982ef4.png)

**Comment by oischinger** [comment]
Hi @Benleni17 
If you install the [vicare custom component via HACS](https://github.com/oischinger/ha_vicare/blob/master/README.md)
and provide the diagnostics information (you can find a button to dump diagnostics on the Integration page) you will get the complete dump of data which Viessmann provides. If you search this file for the data your interested in we might be able to help.

**Comment by Benleni17** [comment]
Do I have to uninstall the official vicare integration? I can't find any vicare integration via HACS

**Comment by oischinger** [comment]
No, so far you need to add this repos in HACS as a custom repository. It will be in HACS by default once it reached some more majurity.

**Comment by oischinger** [comment]
Exactly

**Comment by Benleni17** [comment]
Unfortunately, the API does not release any electrical output of the heat pump. But the data of my Viessmann ventilation system, which is currently displayed in the ViCareapp but not in the HA. Can these codes be added to the ViCare HA?

Why is no power displayed in the API even though I can view the power data on the Viessmann website?

`            "apiVersion": 1,
            "commands": {},
            "deviceId": "0",
            "feature": "ventilation.operating.programs.active",
            "gatewayId": "################",
            "isEnabled": true,
            "isReady": true,
            "properties": {
              "value": {
                "type": "string",
                "value": "levelTwo"
              }
            },
            "timestamp": "2023-04-11T12:00:13.292Z",
            "uri": "https://api.viessmann.com/iot/v1/equipment/installations/#######/gateways/################/devices/0/features/ventilation.operating.programs.active"

         "apiVersion": 1,
            "commands": {},
            "deviceId": "0",
            "feature": "ventilation",
            "gatewayId": "################",
            "isEnabled": true,
            "isReady": true,
            "properties": {
              "active": {
                "type": "boolean",
                "value": true
              }
            },
            "timestamp": "2023-04-11T01:13:46.081Z",
            "uri": "https://api.viessmann.com/iot/v1/equipment/installations/#######/gateways/################/devices/0/features/ventilation"

            "apiVersion": 1,
            "commands": {},
            "deviceId": "0",
            "feature": "ventilation.operating.modes.ventilation",
            "gatewayId": "################",
            "isEnabled": true,
            "isReady": true,
            "properties": {
              "active": {
                "type": "boolean",
                "value": true
              }
            },
            "timestamp": "2023-04-11T01:13:46.081Z",
            "uri": "https://api.viessmann.com/iot/v1/equipment/installations/#######/gateways/################/devices/0/features/ventilation.operating.modes.ventilation"

            "apiVersion": 1,
            "commands": {},
            "deviceId": "0",
            "feature": "ventilation.operating.programs.levelThree",
            "gatewayId": "################",
            "isEnabled": true,
            "isReady": true,
            "properties": {
              "active": {
                "type": "boolean",
                "value": false
              }
            },
            "timestamp": "2023-04-11T12:00:13.292Z",
            "uri": "https://api.viessmann.com/iot/v1/equipment/installations/#######/gateways/################/devices/0/features/ventilation.operating.programs.levelThree"

            "apiVersion": 1,
            "commands": {},
            "deviceId": "0",
            "feature": "ventilation.operating.programs.levelFour",
            "gatewayId": "################",
            "isEnabled": true,
            "isReady": true,
            "properties": {
              "active": {
                "type": "boolean",
                "value": false
              }
            },
            "timestamp": "2023-04-11T01:13:46.082Z",
            "uri": "https://api.viessmann.com/iot/v1/equipment/installations/#######/gateways/################/devices/0/features/ventilation.operating.programs.levelFour"



`

**Comment by Benleni17** [comment]
push :)

**Comment by lukx** [comment]
@Benleni17 I have found that Viessmann's API **does not** expose the power consumption data with the scopes we use for the ha_vicare integration, therefore they do not appear here. So unfortunately the consumption is invisible outside of the official Vicare App or Website unless Viessmann decides to review their product policies to be less restricted.
