### ISSUE TITLE
Adding gas to energy dashboard error

### ISSUE THREAD

**Issue by Iminet72** [oischinger/ha_vicare#134]
Yesterday, the Vissamann device data disappeared from the energy dashboard. I tried to add it again but I don't see any m3 data for my two boilers.

**Comment by Iminet72** [comment]
I managed to find an error. The data unit has changed. After fixing the error, it appears again on the dashboard

**Comment by oischinger** [comment]
Interesting finding.
We take the unit from whatever the API gives us.
Did it change on the API or dis you change it somewhere manually

**Comment by Iminet72** [comment]
The problem is that I only noticed it now and it didn't work for about 2 days. In the meantime, I corrected quite a few mistakes. I also tested other integrations.
Definitely not manually. I improved the statistics in their development tool, but I don't remember what. It is certain that it was not a manual modification, but an offered repair.
