### ISSUE TITLE
Higher PyViCare version than official integration?

### ISSUE THREAD

**Issue by crazyfx1** [oischinger/ha_vicare#140]
I want to test the newer PyViCare version and also implement some features. Is it possible to have a higher PyViCare version than the official component? I get an error when I just upgrade the version in the custom component, even though the official integration is not running.

**Comment by oischinger** [comment]
it is possible if you add it to the manifest but PyVicare introduced a breaking change recently. I just fixed that with https://github.com/oischinger/ha_vicare/pull/143
