### ISSUE TITLE
Climate component broken in current HA version (0.90)

### ISSUE THREAD

**Issue by drgrandios** [oischinger/ha_vicare#17]
Seems to be the same as this:

https://github.com/jamiewalters/python-verisure-climate/issues/4

![Screenshot_2019-04-03 Home Assistant](https://user-images.githubusercontent.com/28082191/55492992-7b66c200-5638-11e9-9ab8-63d21a58a585.png)

**Comment by drgrandios** [comment]
The following updated import statement in `climate.py` fixes the issue:

```python
"""
 ViCare climate device.
 """
 
 import logging
 
 from homeassistant.components.climate import (
     ClimateDevice)
 from homeassistant.components.climate.const import (
         SUPPORT_TARGET_TEMPERATURE, SUPPORT_AWAY_MODE,
     SUPPORT_HOLD_MODE, SUPPORT_OPERATION_MODE, SUPPORT_ON_OFF,
     STATE_HEAT, STATE_ECO, STATE_AUTO)
 from homeassistant.const import (
     TEMP_CELSIUS, TEMP_FAHRENHEIT, ATTR_TEMPERATURE,
     CONF_USERNAME, CONF_PASSWORD, CONF_NAME, PRECISION_WHOLE,STATE_OFF)
```

**Comment by oischinger** [comment]
I guess that was solved. Note that 0.92 also breaks this component.
A fix is available here: https://github.com/oischinger/ha_vicare/commit/b8ca9eb33234c0d339408c3925dad134584ae09a
