### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by pepeEL** [oischinger/ha_vicare#20]
Hi
Is any chance to add support multilanguage to this component ? I am ready to help with translation POLISH language.

**Comment by oischinger** [comment]
Hi @pepeEL 
What translations are you expecting?
Actually at least now, when we've finally migrated to the new Climate component of Home Assistant all the hvac modes and presets are default HA strings and they are already translated in the Web UI.

Only for the sensors part no translations are available.
