### ISSUE TITLE
Problem with gaz devices - Temperature is not a number: error

### ISSUE THREAD

**Issue by somm15** [oischinger/ha_vicare#22]
My boiler has no room sensor and the supply temperature is not available either. 
So any click on the heating part in HA results in an error. 

I would suggest another if with 
- getCurrentDesiredTemperature (what's actually displayed in the app)
The only other temperature I have is:
- getBoilerTemperature (temperature inside the boiler)
But this one is currently in "GazBoiler" object because I don't think it's available for heat pumps (TBC). 
 
FYI, I also added getBurnerModulation() 
I believe this is available only for gaz burners, so I added it to the GazBoiler object.

I noticed also several new API endpoint about solar. Didn't implement it yet.

**Comment by oischinger** [comment]
I already fixed at least the exception on the HA official repo.
I'll have to sync it back to this repo.
But I guess it makes sense to also check the other temperatures even though the boiler temperature might not be too useful for display in the thermostat ui

**Comment by oischinger** [comment]
I updated the source to match the 0.99 release
