### ISSUE TITLE
Error on latest HA / Fix in PyVicare

### ISSUE THREAD

**Issue by somm15** [oischinger/ha_vicare#24]
Hi !
I had an error with the latest HA because of simplejson missing. 
I tried not to rely on this library but adding it was the only way I found to solve the error. 
I published PyVicare 0.1.7 with the fix. I also merge the latest PR. 

Feel free to test (I insist :-) )and integrate.

Regards,

**Comment by oischinger** [comment]
I kindof overlooked this issue.
Here's the PR: https://github.com/home-assistant/home-assistant/pull/31672
