### ISSUE TITLE
Default scan interval still 15 minutes

### ISSUE THREAD

**Issue by crazyfx1** [oischinger/ha_vicare#29]
I'm using the new custom component and the scan interval seems to be still 15 minutes on default. I dont have any scan_interval set in my configuration.yaml

I suspect it might be because of the SCAN_INTERVAL in water_heater.py and climate.py
https://github.com/oischinger/ha_vicare/blob/697faa700fe2f2cd0c9a39d52b52d0c068ad7860/vicare/water_heater.py#L46

**Comment by adorobis** [comment]
Yes, you need to change to whatever is confirmed to work. Does 60 work if you have both climate and water_heater components?

**Comment by geertmeersman** [comment]
The scan interval of the vicare component is not taken over from the configuration, but is hardcoded indeed in the component now as a quickfix.
Btw I had to increase it to 20 minutes as 15 did not last during 24 hours.

**Comment by adorobis** [comment]
@geertmeersman 
You can already implement modification in the PiVicare component as per this pull request:
https://github.com/somm15/PyViCare/pull/28
by implementing it the component will make only 1 api call and cache all parameters therefore you can go do to refresh every 2 minutes (or lower to be confirmed)

**Comment by oischinger** [comment]
Sorry, I messed up a merge here.
Please see the latest changes on master.
The previous 15min scan interval is now removed and I only set the update rate of pyvicare in init.py

**Comment by adorobis** [comment]
Thanks Hans! So we can now set it up as a parameter in configuration.yaml, right? Have you also already implemented changes required to benefit from the latest batching changes in the PyVicare component?

**Comment by oischinger** [comment]
Exactly. scan_interval: 60 is the default by the way. Change the number in your yaml to whatever you need
