### ISSUE TITLE
Attributes suddenly missing from ViCare climate component

### ISSUE THREAD

**Issue by Jpsy** [oischinger/ha_vicare#30]
I just found that a bunch of rather useful attributes went suddenly missing from the ViCare climate integration in HA: 
* supply_temperature
* return_temperature
* outside_temperature
* circulationpump_active

Is this vanishing an expected behavior?   
I can still see most of these attributes in the ViCare app (except for outside temp).

Unfortunately I do not know, when these attributes vanished. I just found them missing today.
They were all quite important in monitoring the condition of the Viessmann heating.

**Comment by Jpsy** [comment]
Oh sorry, just minutes after writing, I found them.
They are now sensors on their own instead of attributes (which is great).  
Thanks for this improvement!

**Comment by crazyfx1** [comment]
The change is also described in the release notes in the "breaking changes" section ;)
https://www.home-assistant.io/blog/2020/07/01/release-112/

**Comment by Jpsy** [comment]
Yes, I found it there to. Shame on me. ;)
