### ISSUE TITLE
Add support for installation via HACS

### ISSUE THREAD

**Issue by woehrl01** [oischinger/ha_vicare#31]
Currently, the installation is done by manually downloading the repo and putting the `vicare` folder under `custom_components` it would be great to allow the installation (and updating) via HACS. See: https://hacs.xyz/docs/publish/start

This requires moving the `vicare` folder to an additional folder `custom_components`. (`content_in_root: false`)

**Comment by geertmeersman** [comment]
Hi Lucas, why would you use hacs? There is already an official integration?
https://www.home-assistant.io/integrations/vicare/

**Comment by woehrl01** [comment]
@geertmeersman I have used the offical integration in the past with great success. Unfortunatly the offical integration is lacking the `vicare.vicare_mode` service to manually enable and disable the heating. At least I can't disable the heating, while keeping the hot water.

**Comment by oischinger** [comment]
@woehrl01 sorry for not being resposive lately.
I'll merge the vicare_mode service to HA core asap then there is no need for hacs. There's not much development on the custom component anyway

**Comment by woehrl01** [comment]
@oischinger Awesome, sounds great! Thanks! 👍🏼

**Comment by oischinger** [comment]
here's the PR: https://github.com/home-assistant/core/pull/44563
I'm closing this ticket
