### ISSUE TITLE
Invalid config :  vicare.sensor 

### ISSUE THREAD

**Issue by as9441** [oischinger/ha_vicare#33]
I have this problem, can you help me?

Logger: homeassistant.setup
Source: setup.py:280
First occurred: 11:36:27 (1 occurrences)
Last logged: 11:36:27

Unable to prepare setup for platform vicare.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

**Comment by oischinger** [comment]
Hi, the latest commit on master should fix that: 2b1e7644f916520b3a93e0937997ab0cecacc90c

Anyway: Please don't use this custom component if you have no specific reason to do so. The same code is also integrated in the Home Assistant releases
