### ISSUE TITLE
Support - for Fuelcell heating type

### ISSUE THREAD

**Issue by RafSchandevyl** [oischinger/ha_vicare#34]
Hi,
In the piVicare api librarary there is support for fuelcell heating type.  Would it be possible to integrate this also in the ha_vicare integration ?

Regards
Raf

**Comment by oischinger** [comment]
Hi. I guess it is but it's quite impossible for me to implement without a device.
Feel free to contribute however.

**Comment by RafSchandevyl** [comment]
Hi,

 

The problem is that I have no idea how to start contributing.  

 

What I can offer is to test it.  From what I see the component is a wrapper around the pyVicare api library.  So if you could provide the wrapper I’m willing to test it.

 

I’m also willing to give you access to my device as a base for testing.

 

Regards

Raf

**Comment by oischinger** [comment]
I have to admit that I do also not have a good understanding on how fuel cell heating works, so I guess it'll be hard for me to map the parameters to the climate device.

Also: the current integration should also support any Viessmann heater at least to a very basic functionality.

Does it not work at all for you?

**Comment by RafSchandevyl** [comment]
Yes it works, but only for the gas burner.

 

I have good understanding of the fuelcell, but don’t have a development environment for ha.  

 

I’ll try to create the code for the fuel cell.   Could you then upload it to the repository (I haven’t had the time to check how I need to work with the git.

 

Regards

Raf

**Comment by oischinger** [comment]
Sure. I guess I need to understand how you want the fuel cell to be represented in HA. Is it just a number of sensors or do you also want to control something

**Comment by RafSchandevyl** [comment]
I’ll check the api information.  

 

I think for the moment the api has just a bit of sensors.  No control possibility at this moment (This is what I Think.  In need to verify)

 

Give me some time, I’ll try to create the basic files that ore needed + changes to the existing files.

 

Regards

Raf

**Comment by oischinger** [comment]
Additional sensors should be fairly easy to.add.
What I would need to know is the pyvicare api call to get the sensor, the respective unit (e.g.kWh) and maybe thebtype.of sensor in HA (binary sensor, sensor and what category)

**Comment by RafSchandevyl** [comment]
Hi,

 

I updated these files with the needed sensors.  There is a lot more info available, but this is what I need.  

 

The problem is that I still need to find out how I can get this into the official distribution.  For me it’s the first time that I’m working with github.  So I need to find out.

 

It would be great if you could publish this already.

 

Regards

Raf

**Comment by oischinger** [comment]
Fuelcell supporot is already available in Home Assistant Core.
Also: a major update to latest PyVicare could be necessary. Will be contributed to HA Core soon.
https://github.com/oischinger/ha_vicare/pull/43
