### ISSUE TITLE
Unable to decode data from ViCare server

### ISSUE THREAD

**Issue by Zixim** [oischinger/ha_vicare#35]
anyone else ?
```
Logger: homeassistant.components.vicare.water_heater
Source: components/vicare/water_heater.py:98
Integration: Viessmann ViCare (documentation, issues)
First occurred: March 16, 2021, 1:16:48 PM (1 occurrences)
Last logged: March 16, 2021, 1:16:48 PM

Unable to decode data from ViCare server
```

**Comment by geertmeersman** [comment]
All seems fine here, did you try to  restart HA? I know Viessmann is doing  currently some maintenance on their servers.

**Comment by Zixim** [comment]
it was most likely a combination of ViCare maintenance & a wifi hickup in the lan, the thing resolved itself while I was chasing the problem.
This makes me think if there couldn't be a way for the integration to warn us of upcoming/current api interruptions ?

**Comment by oischinger** [comment]
Warning would be great but so far I did not see something like this in the json data.
If you know anything about data that could help us please let me know. Closing this for now

**Comment by Zixim** [comment]
the app (sometimes) shows upcoming interruptions doubt the info would be available through their api.
