### ISSUE TITLE
New developer portal is  live

### ISSUE THREAD

**Issue by geertmeersman** [oischinger/ha_vicare#36]
Just received the email that the developer portal is live...
Now waiting 24h to have the API key available,  but it looks  promising.
Someone that already has an API key and played with it?

![image](https://user-images.githubusercontent.com/1844091/116865013-1d3aad80-ac09-11eb-849e-5f85fd9029f8.png)

**Comment by geertmeersman** [comment]
Ok, saw that they already picket it up on the PyVicare https://github.com/somm15/PyViCare/issues/74

**Comment by adorobis** [comment]
Any chance to have a new release of the HA integration to use the V2 API? It should be soon ready on PyViCare https://github.com/somm15/PyViCare/pull/88

**Comment by oischinger** [comment]
I have some trouble finding free time to work on this recently but I definitely will check it out asap. The PR looks promising.

By the way I am not 100% sure that the old integration will stop working on the 15th. Let's watch what happens.

**Comment by adorobis** [comment]
Looks like viessmann is re-confirming in a new e-mail that the old API keys will expire on 15th July.
