### ISSUE TITLE
Missing 'pkce' module when loading on HA

### ISSUE THREAD

**Issue by krahabb** [oischinger/ha_vicare#45]
Hello,
I've just re-enabled vicare (official) integration in my HA after updating the core (running on venv) to 2021.8.0
but the process failed since the python module 'pkce' is missing (or at least it was) in my installation.
I think there's a dependency missing here or maybe in PyViCare: I'm not really expert on python dependency requirements declaration but I've checked this repository manifest and it only requires pyvicare.
I'm not sure if I should open an issue in official HA but since I understand this is where everything starts I've come here to signal the issue.
After manually installing  'pkce' in my venv everything looks fine: vicare gets loaded correctly.

Thank you for your work on Viessmann integration!

**Comment by oischinger** [comment]
That's weird. I believe you#re the first one reporting this. I also just installed a fresh HA Core container and it had all dependencies automatically pulled.
How exactly is this reproduceable? checkout HA from source, run the venv and start HA?

**Comment by krahabb** [comment]
I had my environment already in my place since 1 year so it's not a new installation. 
Keep in my mind vicare was previously enabled and working until 15 of July then I just disabled it by commenting some configuration.yaml
Now, I've decided to dig into it a bit and I see my venv reports PyViCare 1.0.0 ( through 'pip list')  while the last available version I see on Pypi is 2.4.0
The official vicare integration reports 'PyViCare==1.0.0' as dependency so my venv looks formally correct. 
Maybe PyViCare 1.0.0 is missing 'pkce' as a requirement...(like if it's a transient bug)

**Comment by woehrl01** [comment]
That could likely be. I just merged a PR regarding pkce: https://github.com/somm15/PyViCare/pull/157

**Comment by oischinger** [comment]
Great. Maybe this isn't a problem for everyone because some people have other integrations requiring pkce?

**Comment by woehrl01** [comment]
That sounds pretty likely 👍🏽

**Comment by krahabb** [comment]
I'll close this since it doesn't appear as an issue for no-one else ;)
Thank you!
