### ISSUE TITLE
Add attribute for DomesticHotWaterPump state

### ISSUE THREAD

**Issue by paradix** [oischinger/ha_vicare#46]
The Viessmann API returns a value for the DomesticHotWaterPump status. 
Would it be possible to add this an attribute for use withing HA?

**Comment by oischinger** [comment]
Sure, seems PyVicare exposes getDomesticHotWaterPumpActive already. I'll try to add it.
Right now there's however a larger refactoring ongoing (https://github.com/oischinger/ha_vicare/pull/43) which we need to be integrated before we can add new features.

**Comment by oischinger** [comment]
It's now part of this custom component and soon HA core
