### ISSUE TITLE
water_heater.set_temperature not functioning

### ISSUE THREAD

**Issue by Zixim** [oischinger/ha_vicare#47]
water_heater.set_temperature was working properly in 2021.8.0
About 4 days ago, it stopped working.
HA is now on core-2021.8.7, I have downgraded to 8.0 - no joy

There is no error in the logs, just the DHW temp doesn’t get set.

Other functions ( like setting the heating temp) , work just fine.

**Comment by woehrl01** [comment]
@Zixim There has been an API change from Viessmann happening in the last few days.  The issue is currently tracked in the underlying library: https://github.com/somm15/PyViCare/issues/167

**Comment by woehrl01** [comment]
@Zixim I just published `2.7.1` of PyViCare with the necessary fix. To make things work in Home Assistant a PR needs to be done there.
