### ISSUE TITLE
Integrate with new home assistant energy feature

### ISSUE THREAD

**Issue by woehrl01** [oischinger/ha_vicare#48]
We should add a integration with the new energy feature for home assistant:

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by oischinger** [comment]
There is some confusion about what unit Viessmann is delivering (kWh or m³)
See also this issue in HA Core: https://github.com/home-assistant/core/issues/50413

Also: currently HA only supports m³ for gas boilers. I created a feature request to also support kWh:
https://community.home-assistant.io/t/energy-dashboard-allow-gas-as-kwh/339891/8

Sensors for solar should however be fairly easy to implement.

**Comment by oischinger** [comment]
resolved some time ago
