### ISSUE TITLE
config flow branch : after setup, discovers again.

### ISSUE THREAD

**Issue by Zixim** [oischinger/ha_vicare#50]
Set up the integration (user & pass & api), restarted HA.
Now I get a 2nd "discovered" device, I have just 1 boiler on the network.
![image](https://user-images.githubusercontent.com/7814664/131968446-a8419bc2-52ee-44f4-8bc8-c754d0bc3ab7.png)

**Comment by oischinger** [comment]
Resolved with recent changes on the config_flow branch
