### ISSUE TITLE
Add unique_id to climate and water_heater

### ISSUE THREAD

**Issue by HerrDepence** [oischinger/ha_vicare#54]
Hey there,

currently the climate and water_heater components doesn't generate a unique_id.
Could you please add the property?

Thanks,
HerrDepence

**Comment by oischinger** [comment]
are you talking about the current master or the branch config_flow?
see the discussion here: https://github.com/oischinger/ha_vicare/pull/43#discussion_r721603257

**Comment by HerrDepence** [comment]
I was talking about the version which is currently available in home assistant. It might be the dev branch which is linked on the [integration website](https://www.home-assistant.io/integrations/vicare/). But it the unique_id property is missing in the master as well for these components.

**Comment by oischinger** [comment]
Could you do me a favor and test this branch if the issue is resolved for you: https://github.com/oischinger/ha_vicare/pull/43

**Comment by HerrDepence** [comment]
That solves the issue, thanks!
Guess we'll stay on the WIP branche before everything's merged and done.
