### ISSUE TITLE
Missing Version Number

### ISSUE THREAD

**Issue by la-sve** [oischinger/ha_vicare#56]
While using Home Assistant 2021.9.7, the integration is not been loaded because of a missing version number within the manifest.json.

Error:
[homeassistant.loader] The custom integration 'vicare' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/20

Solution would be:
Add the attribute "version" to the manifest.json

**Comment by crazyfx1** [comment]
Seems like you are not using the newest version. The "version" field was added in july, please update your installation.

**Comment by crazyfx1** [comment]
Sorry, my bad, the config_flow branch doesnt have the version key.

**Comment by oischinger** [comment]
Sorry for that. Must have happened during the sync with the Home assistant PR. The integration for Home Assistant core cannot have a version field while custom components must have the field
