### ISSUE TITLE
missing units in temperature values

### ISSUE THREAD

**Issue by Zixim** [oischinger/ha_vicare#63]
After updating to energy-support, I noticed that the graphs in lovelace for `sensor.vicare_supply_temperature` and `sensor.vicare_outside_temperature` look like this : 
![image](https://user-images.githubusercontent.com/7814664/137481370-58e0b07e-c481-41c1-8628-0e3b9091756d.png)

They used to look like a line graph similar to : 
![image](https://user-images.githubusercontent.com/7814664/137481527-833bf83a-3d56-4ae4-8842-dd10d2b48e19.png)

Could this be because units of measurement are missing in `sensor.vicare_supply_temperature` and `sensor.vicare_outside_temperature` ?
![image](https://user-images.githubusercontent.com/7814664/137481746-4c30691d-86ff-4d55-8c24-dc044e0d6de1.png)
versus
![image](https://user-images.githubusercontent.com/7814664/137481792-ec11c1f7-030f-40fe-b55e-3ff02fe23da0.png)

**Comment by oischinger** [comment]
oh, thanks for reporting that.
I just updated the branch with a fix
