### ISSUE TITLE
Commit "Update to follow latest HA Core PRs" breaks the integration

### ISSUE THREAD

**Issue by admin-lm** [oischinger/ha_vicare#66]
Adding the Integration throws this error:

Logger: homeassistant.components.http.view
Source: components/http/view.py:59
Integration: HTTP (documentation, issues)
First occurred: 10:31:14 (1 occurrences)
Last logged: 10:31:14

Unable to serialize to JSON: Object of type HeatingType is not JSON serializable {'type': 'form', 'flow_id': 'a54e529417c241b1908b07f4b8a99426', 'handler': 'vicare', 'step_id': 'user', 'data_schema': [{'type': 'string', 'name': 'username', 'required': True}, {'type': 'string', 'name': 'password', 'required': True}, {'type': 'string', 'name': 'client_id', 'required': True}, {'type': 'select', 'options': [(<HeatingType.auto: 'auto'>, <HeatingType.auto: 'auto'>), ('gas', 'gas'), ('heatpump', 'heatpump'), ('fuelcell', 'fuelcell')], 'name': 'heating_type', 'optional': True, 'default': <HeatingType.auto: 'auto'>}, {'type': 'string', 'name': 'name', 'optional': True, 'default': 'ViCare'}, {'type': 'integer', 'valueMin': 30, 'name': 'scan_interval', 'optional': True, 'default': 60}], 'errors': {}, 'description_placeholders': None, 'last_step': None}

**Comment by oischinger** [comment]
Thanks for pinging me. I updated the master branch again.

Note that I had to change the unique ids of some entities again. This will most likely lead to duplicated entities if you have used thee custom component before.
Just delete the unavailable entities and it should be back to normal
