### ISSUE TITLE
Hybrid Viessmann 222-F: Gas and Heatpump

### ISSUE THREAD

**Issue by stephan-2** [oischinger/ha_vicare#70]
Hello, is it possible to view the entities for gas AND heatpump for the Viessmann 222-F? heating_type: gas shows the gasvalues; heating type: heatpump the values for the heatpump. I need gas AND heatpump.

**Comment by oischinger** [comment]
Hi @stephan-2 ,
Please check out the current master branch of this custom_component and select `hybrid` when setting up the integration.
