### ISSUE TITLE
DHW temperature: null

### ISSUE THREAD

**Issue by ovanbiervliet** [oischinger/ha_vicare#74]
Using 2021.12 with latest ha_vicare, I created an automation to set DHW water (water_heater.vicare_water_0) temp to 10℃ when set to off according to time schedule, and to 48℃ when programmed to heat the water. I believe this is the 'charging' attribute?

The value appears to be set correctly, I can see it in the ViCare app. However, after a number of seconds, it disappears again in HA and shows 'null'. Sometimes the automations are triggered incorrectly, it would be nice to always have the correct value available.

`min_temp: 10
max_temp: 60
current_temperature: 31
temperature: null
target_temp_high: null
target_temp_low: null
charging_active: true
circulation_pump_active: false
friendly_name: ViCare Water 0
supported_features: 1`

**Comment by ovanbiervliet** [comment]
Some further testing: the number changes to null when dhw schedule is set to off, and a valid number when schedule is on. However, with schedule off and setting temp to 48, charging is happening.

**Comment by oischinger** [comment]
that's because the viessmann API doesn't offer the data point when dhw is off.
The HA integration cannot fix that unfortunately. It's an API limitation.
