### ISSUE TITLE
Automations overview  with incorrect last triggered

### ISSUE THREAD

**Issue by PGutti** [oischinger/ha_vicare#76]
The overview screen of automations contains "last triggered" time stamp.  This is often not correct.
The correct last execution time stamp can be seen in the debug/trace dialog.

In the sample below one can see that the automation was executed December 22, but the overview shows December 21.   

![Captura 2021-12-22 a las 19 48 15](https://user-images.githubusercontent.com/40051675/147142130-23b0d6d4-2018-42e1-91ab-5b86ea2fabe8.jpg)
![Captura 2021-12-22 a las 19 48 32](https://user-images.githubusercontent.com/40051675/147142131-a859dbd2-d697-4a08-bc06-ec930ed0c75c.jpg)

**Comment by oischinger** [comment]
this is not really related to the vicare integration and should be reported to HA Core https://github.com/home-assistant/core

**Comment by PGutti** [comment]
Of course! I did not realize i reported it against vicare. 


Saludos
 Grüsse

Peter Güttinger
-––————————————————
