### ISSUE TITLE
Solar Power Data Format

### ISSUE THREAD

**Issue by DarkTempIar** [oischinger/ha_vicare#79]
This is what the Solar Power Data ouptut looks like.
The Values represent each day of the week - is this intentional? Graphs etc. cant use this data format.

![grafik](https://user-images.githubusercontent.com/87620096/150854499-9ae9f8df-a333-49d2-8f90-62a1796be3e0.png)

**Comment by oischinger** [comment]
There's a discussion about it in this HA Core issue:
https://github.com/home-assistant/core/issues/65633

**Comment by oischinger** [comment]
Resolved with https://github.com/oischinger/ha_vicare/pull/92
