### ISSUE TITLE
4 sensors unavailable since 25 of January

### ISSUE THREAD

**Issue by arkadiusz-kopicinski** [oischinger/ha_vicare#80]
Hello

Since yesterday I lost communication with these four sensors. I was trying to rollback HassOS from last snapshot but the same problem occur. Probably this issue is related with some maintenance work on Viessman side.

![image](https://user-images.githubusercontent.com/81807309/151182812-ed4a20b5-5689-4e2a-adcd-ee5fa58dda63.png)

Before rollback sensors were reported as unavailable with additional information:

This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.

If the entity is no longer in use, you can clean it up by removing it.

Regards
Arek

**Comment by oischinger** [comment]
Same problem on my device.
Seems like Viessmann removed them 😠

**Comment by mamoel666** [comment]
Same here. "burner_hours" is my only reason for using the vicare integration :-(

**Comment by woehrl01** [comment]
There is a bug in the current API of Viessmann. See my response in the underlying library: https://github.com/somm15/PyViCare/issues/243#issuecomment-1022909611

**Comment by dennisheitmann** [comment]
Try this workaround, if you have one gas burner (and if you programmed the script/plugin yourself). The `getBurner(0)` function works still:
```
t = device.asAutoDetectDevice()
burner = t.getBurner(0)
parameters['burnerActive'] = burner.getActive()
parameters['burnerHours'] = float(burner.getHours())
parameters['burnerStarts'] = burner.getStarts()
```
[https://gist.github.com/dennisheitmann/c35585b0c00ca109fcb383f01fb5eba1](url)

**Comment by oischinger** [comment]
fixed by integrating latest pyvicare. Thanks @woehrl01 
https://github.com/oischinger/ha_vicare/commit/c281ee49a135648d2dafeeefff50414695d83a0e
