### ISSUE TITLE
Bring back summary sensors

### ISSUE THREAD

**Issue by oischinger** [oischinger/ha_vicare#84]
These sensors were not contributed to HA Core and got lost in this integration.
I'll add them again:
https://github.com/oischinger/ha_vicare/pull/75/files

sorry for the confusion @damianbro

**Comment by oischinger** [comment]
@damianbro and @woehrl01 
As reported in https://github.com/oischinger/ha_vicare/issues/83 there are obviously devices for which both, 
`getGasConsumptionHeatingThisMonth()` and 
`getGasSummaryConsumptionHeatingCurrentMonth()` are both available and are also showing the same data.

Providing sensors for both with nearly identical names does not make much sense.
I wonder if we could handle this in vicare and have one getter that provides either of the data points depending on which is available?

**Comment by oischinger** [comment]
Note to self: Matching HA Core PR is this one: https://github.com/home-assistant/core/pull/64551

**Comment by damianbro** [comment]
> 

I replied in #83 https://github.com/oischinger/ha_vicare/issues/83
