### ISSUE TITLE
Activate one-time-charge: Deactivation?

### ISSUE THREAD

**Issue by lukx** [oischinger/ha_vicare#96]
Hey,
I am using the activate_onetimecharge Button to bypass the limited integration with my solar panels.
Upon researching I found that the official app and pyvicare both support deactivation of the one-time charge, too:
https://github.com/somm15/PyViCare/blob/fb0bde1b3e6cd6b3b071773d6b151e7b57a06c95/PyViCare/PyViCareDevice.py#L276

How would one integrate it into this integration?

**Option 1:** Offer a switch entity 
* Get the status value from `getOneTimeCharge` in pyvicare
* on/off correspond to activate/deactivate oneTimeCharge

Pro: Representing on/off values like a homeassistant user is accustomed
Con: The existing `button` integration would only make limited sense, so this smells like a breaking change or carried-on legacy

**Option 2:** Offer another button to deactivate
Con: Ignores the current status of the one-time charge a bit
Pro: easy integration

Opinions?
(I am going to sketch out a branch with option 1)

**Comment by PaulProjects** [comment]
What is the current status of that feature? Did you create a own solution or is there already a integration featuring that?
