### ISSUE TITLE
Use "button.activate_one_time_charge" via json-API for habridge to use with alexa

### ISSUE THREAD

**Issue by wunderbaum** [oischinger/ha_vicare#97]
When I activate the button in the webpage, I can see it working in the app on the mobile.
Now I tried to access it via ha-bridge to get it activated via Alexa-command "turn warmwater on".
The button is found in the list of entities in ha-brige. But I have no clue what kind of "message" this has to send to homeassistant.
Autogenerated in habridge is:
`{"entityId":"button.activate_one_time_charge","hassName":"HomeAssistant","state":"on"}`
I guess the state parameter _on_ is wrong, but whats the right one?

**Comment by oischinger** [comment]
Hi @wunderbaum 
This is more a question to the ha_bridge devs: how to use a button entity with ha brigde?

Since 1.0.0-beta1 there is now also a switch entity for hot water. maybe you can use this?
